name: inhouse
favicon: null
layout_spectrum: 0.34128296095877886
typography_spectrum: 0.02689517824910581
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dedede'
    - '#6bb66f'
    - '#2a221a'
    - '#457646'
    - '#7b68c0'
  brandStrength: 0
  lightness: 0.6882518832571805
  saturation: 0.3018010351806879
  rhythmicContrast: 0.962422679644078
purpose: []
